FROM centos:7.5.1804

COPY ./conf/nginx.repo /etc/yum.repos.d/
RUN yum -y update \
    && rpm -Uvh http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm \
    && rpm -Uvh http://rpms.famillecollet.com/enterprise/remi-release-7.rpm \
    && yum -y install --enablerepo=remi,remi-php72 \
    php \
    php-pdo \
    php-mysql \
    php-common \
    php-cli \
    php-mbstring \
    php-fpm \
    php-gd \
    php-devel \
    && yum -y install \
    nginx \
    vim \
    git \
    postfix

COPY ./conf/nginx.conf /etc/nginx/conf/
RUN systemctl enable nginx.service \
    && systemctl enable postfix
